title: Mark Vinson # your name (or website title) here
logo: "/images/MV2019.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, Bojour, and Hola, <br>
  Welcome to personal site. I find joy in Border Collies, fish, leftovers, 3rd hand clothes, snow, bikes, and data visualization. I am the Station Chief of the U.S. Geological Survery's Lake Superior Biological Station. I live at the end of a dirt road in northern Wisconsin. 
  <br>
  <br>
  <a href="https://scholar.google.com/citations?user=QMxU4nIAAAAJ&hl=en&oi=ao">Google Scholar Profile</a> 
  <br>
  <a href="http://orcid.org/0000-0001-5256-9539"> ORCid </a> 
  <br>
  <a href="https://twitter.com/superiorliscous"> Twitter </a>


theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
