title: Mark Vinson # your name (or website title) here
logo: "/images/MVinsonPakistan.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, 
  I love fish, Border Collies, leftovers, 3rd hand clothes, snow. bikes, and data visualization.
  
  I currently work as the Station Chief of the U.S. Geological's Survery Lake Superior Biological Station.
  I have studied aquatic plants, invertebrates, and fish from caves, springs, rivers, lakes and wetlands throughout the world. 
  <br><br>
  
  <br><br>
  <a href="https://scholar.google.com/citations?user=QMxU4nIAAAAJ&hl=en&oi=ao">Google Scholar Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
